### ISSUE TITLE
MetamaskInpageProvider - lost connection to MetaMask RpcProvider

### ISSUE THREAD

**Issue by playground** [ChainSafe/metamask-snap-polkadot#108]
MetamaskInpageProvider - lost connection to MetaMask RpcProvider
Error: StreamMiddleware - Unknown response id 2951923128
    at chrome-extension://dlemoigadagaakbfkaflkknjpidifbji/inpage.js:1:276079
    at h.write [as _write] (chrome-extension://dlemoigadagaakbfkaflkknjpidifbji/inpage.js:1:276195)
    at v (chrome-extension://dlemoigadagaakbfkaflkknjpidifbji/inpage.js:1:371323)
    at chrome-extension://dlemoigadagaakbfkaflkknjpidifbji/inpage.js:1:374439
    at h.g.write (chrome-extension://dlemoigadagaakbfkaflkknjpidifbji/inpage.js:1:374466)
    at a.b (chrome-extension://dlemoigadagaakbfkaflkknjpidifbji/inpage.js:1:363746)
    at d (chrome-extension://dlemoigadagaakbfkaflkknjpidifbji/inpage.js:1:95984)
    at a.o.emit (chrome-extension://dlemoigadagaakbfkaflkknjpidifbji/inpage.js:1:98970)
    at _ (chrome-extension://dlemoigadagaakbfkaflkknjpidifbji/inpage.js:1:358585)
    at w (chrome-extension://dlemoigadagaakbfkaflkknjpidifbji/inpage.js:1:358400)

**Comment by mpetrunic** [comment]
Hard to tell, not something our snap should use. Did you build metamask yourself?

We stopped maintaining this snap until Metamask releases snaps in beta as it's quite difficult to use snaps now.

**Comment by BeroBurny** [comment]
stale? re-open if needed.
